# ai: The GPU files the engines read (2026-10-03), out of the generated tree (out/: gen's setup, SPIR-V and blobs):
# ai: each decoder variant's setup and the modules and blobs it names (core/dec/setup.cpp reads objects.pipelines[].module
# ai: as spv/<module>.spv and objects.buffers[].blob as blobs/<blob>.bin), the camera's ingest kernel, the sender's setup
# ai: with its blob (perm.blob) and its send_*.spv (core/tx/gpu_painter.cpp). Nothing else of the tree: its raw SPIR-V,
# ai: the stale blobs of earlier generations and the benchmarks' kernels are not read.
# ai:   liz_gpu_files(<out var> <tree> <variants...>): the files, relative to the tree
function(liz_gpu_files out tree)
  set(files setup/send.json spv/ingest_camera.spv)
  file(GLOB sends RELATIVE ${tree} ${tree}/spv/send_*.spv)
  list(FILTER sends EXCLUDE REGEX "\\.raw\\.spv$")
  list(APPEND files ${sends})
  file(READ ${tree}/setup/send.json send)
  string(JSON perm GET "${send}" perm blob)
  list(APPEND files ${perm})
  foreach(v ${ARGN})
    if(NOT EXISTS ${tree}/setup/${v}.json)
      message(FATAL_ERROR "no GPU setup ${v} in ${tree}")
    endif()
    list(APPEND files setup/${v}.json)
    file(READ ${tree}/setup/${v}.json j)
    string(JSON pipes GET "${j}" objects pipelines)
    string(JSON np LENGTH "${pipes}")
    math(EXPR last "${np} - 1")
    foreach(i RANGE ${last})
      string(JSON id MEMBER "${pipes}" ${i})
      string(JSON m GET "${pipes}" ${id} module)
      list(APPEND files spv/${m}.spv)
    endforeach()
    string(JSON bufs GET "${j}" objects buffers)
    string(JSON nb LENGTH "${bufs}")
    math(EXPR last "${nb} - 1")
    foreach(i RANGE ${last})
      string(JSON id MEMBER "${bufs}" ${i})
      string(JSON type ERROR_VARIABLE none TYPE "${bufs}" ${id} blob)
      if(type STREQUAL "STRING")
        string(JSON b GET "${bufs}" ${id} blob)
        list(APPEND files blobs/${b}.bin)
      endif()
    endforeach()
  endforeach()
  list(REMOVE_DUPLICATES files)
  set(${out} ${files} PARENT_SCOPE)
endfunction()
